version: "3.7"
services:
  httpd:
    build: .
    tty: true
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: src
        target: /usr/local/apache2/htdocs/
    working_dir: /usr/local/apache2/htdocs/
